using System;
using System.Collections.Generic;

namespace MP1_Trilogy_Rando_Generator.Enums
{
    class SpawnRoom
    {
        public readonly uint MLVL;
        public readonly uint PakIndex;
        public readonly uint MREA_ID;
        SpawnRoom(uint MLVL, uint PakIndex, uint MREA_ID)
        {
            this.MLVL = MLVL;
            this.PakIndex = PakIndex;
            this.MREA_ID = MREA_ID;
        }

        public static readonly Dictionary<String, SpawnRoom> randomizerValues = new Dictionary<String, SpawnRoom>()
        {
            { "Chozo Ruins West (Main Plaza)", new SpawnRoom(0x83f6ff6f, 2, 0) }, // Chozo Ruins - Transport to Tallon Overworld North
            { "Chozo Ruins North (Sun Tower)", new SpawnRoom(0x83f6ff6f, 2, 24) }, // Chozo Ruins - Transport to Magmoor Caverns North
            { "Chozo Ruins South (Reflecting Pool, Save Station)", new SpawnRoom(0x83f6ff6f, 2, 62) }, // Chozo Ruins - Transport to Tallon Overworld East
            { "Chozo Ruins South (Reflecting Pool, Far End)", new SpawnRoom(0x83f6ff6f, 2, 63) }, // Chozo Ruins - Transport to Tallon Overworld South
            { "Phendrana Drifts North (Phendrana Shorelines)", new SpawnRoom(0xa8be6291, 3, 0) }, // Phendrana Drifts - Transport to Magmoor Caverns West
            { "Phendrana Drifts South (Quarantine Cave)", new SpawnRoom(0xa8be6291, 3, 29) }, // Phendrana Drifts - Transport to Magmoor Caverns South
            { "Tallon Overworld North (Tallon Canyon)", new SpawnRoom(0x39f2de28, 4, 14) }, // Tallon Overworld - Transport to Chozo Ruins West
            { "Tallon Overworld East (Frigate Crash Site)", new SpawnRoom(0x39f2de28, 4, 22) }, // Tallon Overworld - Transport to Chozo Ruins East
            { "Tallon Overworld West (Root Cave)", new SpawnRoom(0x39f2de28, 4, 23) }, // Tallon Overworld - Transport to Magmoor Caverns East
            { "Tallon Overworld South (Great Tree Hall, Upper)", new SpawnRoom(0x39f2de28, 4, 41) }, // Tallon Overworld - Transport to Chozo Ruins South
            { "Tallon Overworld South (Great Tree Hall, Lower)", new SpawnRoom(0x39f2de28, 4, 43) }, // Tallon Overworld - Transport to Phazon Mines East
            { "Artifact Temple", new SpawnRoom(0x39f2de28, 4, 16) }, // Tallon Overworld - Artifact Temple
            { "Landing Site", new SpawnRoom(0x39f2de28, 4, 0) }, // Tallon Overworld - Landing Site
            { "Phazon Mines East (Main Quarry)", new SpawnRoom(0xb1ac4d65, 5, 0) }, // Phazon Mines - Transport to Tallon Overworld South
            { "Phazon Mines West (Phazon Processing Center)", new SpawnRoom(0xb1ac4d65, 5, 25) }, // Phazon Mines - Transport to Magmoor Caverns South
            { "Magmoor Caverns North (Lava Lake)", new SpawnRoom(0x3ef8237c, 6, 0) }, // Magmoor Caverns - Transport to Chozo Ruins North
            { "Magmoor Caverns West (Monitor Station)", new SpawnRoom(0x3ef8237c, 6, 13) }, // Magmoor Caverns - Transport to Phendrana Drifts North
            { "Magmoor Caverns East (Twin Fires)", new SpawnRoom(0x3ef8237c, 6, 16) }, // Magmoor Caverns - Transport to Tallon Overworld West
            { "Magmoor Caverns East (Magmoor Workstation, Debris)", new SpawnRoom(0x3ef8237c, 6, 26) }, // Magmoor Caverns - Transport to Phazon Mines West
            { "Magmoor Caverns East (Magmoor Workstation, Save Station)", new SpawnRoom(0x3ef8237c, 6, 27) } // Magmoor Caverns - Transport to Phendrana Drifts South
        };

        public static readonly Dictionary<String, SpawnRoom> plandomizerValues = new Dictionary<String, SpawnRoom>()
        {
            { "Frigate:Exterior Docking Hangar", new SpawnRoom(0x158efe17, 1, 0) },
            { "Frigate:Air Lock", new SpawnRoom(0x158efe17, 1, 1) },
            { "Frigate:Deck Alpha Access Hall", new SpawnRoom(0x158efe17, 1, 2) },
            { "Frigate:Deck Alpha Mech Shaft", new SpawnRoom(0x158efe17, 1, 3) },
            { "Frigate:Emergency Evacuation Area", new SpawnRoom(0x158efe17, 1, 4) },
            { "Frigate:Connection Elevator to Deck Alpha", new SpawnRoom(0x158efe17, 1, 5) },
            { "Frigate:Deck Alpha Umbilical Hall", new SpawnRoom(0x158efe17, 1, 6) },
            { "Frigate:Biotech Research Area 2", new SpawnRoom(0x158efe17, 1, 7) },
            { "Frigate:Map Facility", new SpawnRoom(0x158efe17, 1, 8) },
            { "Frigate:Main Ventilation Shaft F", new SpawnRoom(0x158efe17, 1, 9) },
            { "Frigate:Connection Elevator to Deck Beta", new SpawnRoom(0x158efe17, 1, 10) },
            { "Frigate:Main Ventilation Shaft E", new SpawnRoom(0x158efe17, 1, 11) },
            { "Frigate:Deck Beta Conduit Hall", new SpawnRoom(0x158efe17, 1, 12) },
            { "Frigate:Main Ventilation Shaft D", new SpawnRoom(0x158efe17, 1, 13) },
            { "Frigate:Biotech Research Area 1", new SpawnRoom(0x158efe17, 1, 14) },
            { "Frigate:Main Ventilation Shaft C", new SpawnRoom(0x158efe17, 1, 15) },
            { "Frigate:Deck Beta Security Hall", new SpawnRoom(0x158efe17, 1, 16) },
            { "Frigate:Connection Elevator to Deck Beta 2", new SpawnRoom(0x158efe17, 1, 17) },
            { "Frigate:Subventilation Shaft Section A", new SpawnRoom(0x158efe17, 1, 18) },
            { "Frigate:Main Ventilation Shaft B", new SpawnRoom(0x158efe17, 1, 19) },
            { "Frigate:Biohazard Containment", new SpawnRoom(0x158efe17, 1, 20) },
            { "Frigate:Deck Gamma Monitor Hall", new SpawnRoom(0x158efe17, 1, 21) },
            { "Frigate:Subventilation Shaft Section B", new SpawnRoom(0x158efe17, 1, 22) },
            { "Frigate:Main Ventilation Shaft A", new SpawnRoom(0x158efe17, 1, 23) },
            { "Frigate:Deck Beta Transit Hall", new SpawnRoom(0x158efe17, 1, 24) },
            { "Frigate:Reactor Core", new SpawnRoom(0x158efe17, 1, 25) },
            { "Frigate:Cargo Freight Lift to Deck Gamma", new SpawnRoom(0x158efe17, 1, 26) },
            { "Frigate:Reactor Core Entrance", new SpawnRoom(0x158efe17, 1, 25) },
            { "Chozo:Transport to Tallon Overworld North", new SpawnRoom(0x83f6ff6f, 2, 0) },
            { "Chozo:Ruins Entrance", new SpawnRoom(0x83f6ff6f, 2, 1) },
            { "Chozo:Main Plaza", new SpawnRoom(0x83f6ff6f, 2, 2) },
            { "Chozo:Ruined Fountain Access", new SpawnRoom(0x83f6ff6f, 2, 3) },
            { "Chozo:Ruined Shrine Access", new SpawnRoom(0x83f6ff6f, 2, 4) },
            { "Chozo:Nursery Access", new SpawnRoom(0x83f6ff6f, 2, 5) },
            { "Chozo:Plaza Access", new SpawnRoom(0x83f6ff6f, 2, 6) },
            { "Chozo:Piston Tunnel", new SpawnRoom(0x83f6ff6f, 2, 7) },
            { "Chozo:Ruined Fountain", new SpawnRoom(0x83f6ff6f, 2, 8) },
            { "Chozo:Ruined Shrine", new SpawnRoom(0x83f6ff6f, 2, 9) },
            { "Chozo:Eyon Tunnel", new SpawnRoom(0x83f6ff6f, 2, 10) },
            { "Chozo:Vault", new SpawnRoom(0x83f6ff6f, 2, 11) },
            { "Chozo:Training Chamber", new SpawnRoom(0x83f6ff6f, 2, 12) },
            { "Chozo:Arboretum Access", new SpawnRoom(0x83f6ff6f, 2, 13) },
            { "Chozo:Meditation Fountain", new SpawnRoom(0x83f6ff6f, 2, 14) },
            { "Chozo:Tower of Light Access", new SpawnRoom(0x83f6ff6f, 2, 15) },
            { "Chozo:Ruined Nursery", new SpawnRoom(0x83f6ff6f, 2, 16) },
            { "Chozo:Vault Access", new SpawnRoom(0x83f6ff6f, 2, 17) },
            { "Chozo:Training Chamber Access", new SpawnRoom(0x83f6ff6f, 2, 18) },
            { "Chozo:Arboretum", new SpawnRoom(0x83f6ff6f, 2, 19) },
            { "Chozo:Magma Pool", new SpawnRoom(0x83f6ff6f, 2, 20) },
            { "Chozo:Tower of Light", new SpawnRoom(0x83f6ff6f, 2, 21) },
            { "Chozo:Save Station 1", new SpawnRoom(0x83f6ff6f, 2, 22) },
            { "Chozo:North Atrium", new SpawnRoom(0x83f6ff6f, 2, 23) },
            { "Chozo:Transport to Magmoor Caverns North", new SpawnRoom(0x83f6ff6f, 2, 24) },
            { "Chozo:Sunchamber Lobby", new SpawnRoom(0x83f6ff6f, 2, 25) },
            { "Chozo:Gathering Hall Access", new SpawnRoom(0x83f6ff6f, 2, 26) },
            { "Chozo:Tower Chamber", new SpawnRoom(0x83f6ff6f, 2, 27) },
            { "Chozo:Ruined Gallery", new SpawnRoom(0x83f6ff6f, 2, 28) },
            { "Chozo:Sun Tower", new SpawnRoom(0x83f6ff6f, 2, 29) },
            { "Chozo:Transport Access North", new SpawnRoom(0x83f6ff6f, 2, 30) },
            { "Chozo:Sunchamber Access", new SpawnRoom(0x83f6ff6f, 2, 31) },
            { "Chozo:Gathering Hall", new SpawnRoom(0x83f6ff6f, 2, 32) },
            { "Chozo:Totem Access", new SpawnRoom(0x83f6ff6f, 2, 33) },
            { "Chozo:Map Station", new SpawnRoom(0x83f6ff6f, 2, 34) },
            { "Chozo:Sun Tower Access", new SpawnRoom(0x83f6ff6f, 2, 35) },
            { "Chozo:Hive Totem", new SpawnRoom(0x83f6ff6f, 2, 36) },
            { "Chozo:Sunchamber", new SpawnRoom(0x83f6ff6f, 2, 37) },
            { "Chozo:Watery Hall Access", new SpawnRoom(0x83f6ff6f, 2, 38) },
            { "Chozo:Save Station 2", new SpawnRoom(0x83f6ff6f, 2, 39) },
            { "Chozo:East Atrium", new SpawnRoom(0x83f6ff6f, 2, 40) },
            { "Chozo:Watery Hall", new SpawnRoom(0x83f6ff6f, 2, 41) },
            { "Chozo:Energy Core Access", new SpawnRoom(0x83f6ff6f, 2, 42) },
            { "Chozo:Dynamo Access", new SpawnRoom(0x83f6ff6f, 2, 43) },
            { "Chozo:Energy Core", new SpawnRoom(0x83f6ff6f, 2, 44) },
            { "Chozo:Dynamo", new SpawnRoom(0x83f6ff6f, 2, 45) },
            { "Chozo:Burn Dome Access", new SpawnRoom(0x83f6ff6f, 2, 46) },
            { "Chozo:West Furnace Access", new SpawnRoom(0x83f6ff6f, 2, 47) },
            { "Chozo:Burn Dome", new SpawnRoom(0x83f6ff6f, 2, 48) },
            { "Chozo:Furnace", new SpawnRoom(0x83f6ff6f, 2, 49) },
            { "Chozo:East Atrium Access", new SpawnRoom(0x83f6ff6f, 2, 50) },
            { "Chozo:Crossway Access West", new SpawnRoom(0x83f6ff6f, 2, 51) },
            { "Chozo:Hall of the Elders", new SpawnRoom(0x83f6ff6f, 2, 52) },
            { "Chozo:Crossway", new SpawnRoom(0x83f6ff6f, 2, 53) },
            { "Chozo:Reflecting Pool Access", new SpawnRoom(0x83f6ff6f, 2, 54) },
            { "Chozo:Elder Hall Access", new SpawnRoom(0x83f6ff6f, 2, 55) },
            { "Chozo:Crossway Access South", new SpawnRoom(0x83f6ff6f, 2, 56) },
            { "Chozo:Elder Chamber", new SpawnRoom(0x83f6ff6f, 2, 57) },
            { "Chozo:Reflecting Pool", new SpawnRoom(0x83f6ff6f, 2, 58) },
            { "Chozo:Save Station 3", new SpawnRoom(0x83f6ff6f, 2, 59) },
            { "Chozo:Transport Access South", new SpawnRoom(0x83f6ff6f, 2, 60) },
            { "Chozo:Antechamber", new SpawnRoom(0x83f6ff6f, 2, 61) },
            { "Chozo:Transport to Tallon Overworld East", new SpawnRoom(0x83f6ff6f, 2, 62) },
            { "Chozo:Transport to Tallon Overworld South", new SpawnRoom(0x83f6ff6f, 2, 63) },
            { "Phendrana:Transport to Magmoor Caverns West", new SpawnRoom(0xa8be6291, 3, 0) },
            { "Phendrana:Shoreline Entrance", new SpawnRoom(0xa8be6291, 3, 1) },
            { "Phendrana:Phendrana Shorelines", new SpawnRoom(0xa8be6291, 3, 2) },
            { "Phendrana:Temple Entryway", new SpawnRoom(0xa8be6291, 3, 3) },
            { "Phendrana:Save Station B", new SpawnRoom(0xa8be6291, 3, 4) },
            { "Phendrana:Ruins Entryway", new SpawnRoom(0xa8be6291, 3, 5) },
            { "Phendrana:Plaza Walkway", new SpawnRoom(0xa8be6291, 3, 6) },
            { "Phendrana:Ice Ruins Access", new SpawnRoom(0xa8be6291, 3, 7) },
            { "Phendrana:Chozo Ice Temple", new SpawnRoom(0xa8be6291, 3, 8) },
            { "Phendrana:Ice Ruins West", new SpawnRoom(0xa8be6291, 3, 9) },
            { "Phendrana:Ice Ruins East", new SpawnRoom(0xa8be6291, 3, 10) },
            { "Phendrana:Chapel Tunnel", new SpawnRoom(0xa8be6291, 3, 11) },
            { "Phendrana:Courtyard Entryway", new SpawnRoom(0xa8be6291, 3, 12) },
            { "Phendrana:Canyon Entryway", new SpawnRoom(0xa8be6291, 3, 13) },
            { "Phendrana:Chapel of the Elders", new SpawnRoom(0xa8be6291, 3, 14) },
            { "Phendrana:Ruined Courtyard", new SpawnRoom(0xa8be6291, 3, 15) },
            { "Phendrana:Phendrana Canyon", new SpawnRoom(0xa8be6291, 3, 16) },
            { "Phendrana:Save Station A", new SpawnRoom(0xa8be6291, 3, 17) },
            { "Phendrana:Specimen Storage", new SpawnRoom(0xa8be6291, 3, 18) },
            { "Phendrana:Quarantine Access", new SpawnRoom(0xa8be6291, 3, 19) },
            { "Phendrana:Research Entrance", new SpawnRoom(0xa8be6291, 3, 20) },
            { "Phendrana:North Quarantine Tunnel", new SpawnRoom(0xa8be6291, 3, 21) },
            { "Phendrana:Map Station", new SpawnRoom(0xa8be6291, 3, 22) },
            { "Phendrana:Hydra Lab Entryway", new SpawnRoom(0xa8be6291, 3, 23) },
            { "Phendrana:Quarantine Cave", new SpawnRoom(0xa8be6291, 3, 24) },
            { "Phendrana:Research Lab Hydra", new SpawnRoom(0xa8be6291, 3, 25) },
            { "Phendrana:South Quarantine Tunnel", new SpawnRoom(0xa8be6291, 3, 26) },
            { "Phendrana:Quarantine Monitor", new SpawnRoom(0xa8be6291, 3, 27) },
            { "Phendrana:Observatory Access", new SpawnRoom(0xa8be6291, 3, 28) },
            { "Phendrana:Transport to Magmoor Caverns South", new SpawnRoom(0xa8be6291, 3, 29) },
            { "Phendrana:Observatory", new SpawnRoom(0xa8be6291, 3, 30) },
            { "Phendrana:Transport Access", new SpawnRoom(0xa8be6291, 3, 31) },
            { "Phendrana:West Tower Entrance", new SpawnRoom(0xa8be6291, 3, 32) },
            { "Phendrana:Save Station D", new SpawnRoom(0xa8be6291, 3, 33) },
            { "Phendrana:Frozen Pike", new SpawnRoom(0xa8be6291, 3, 34) },
            { "Phendrana:West Tower", new SpawnRoom(0xa8be6291, 3, 35) },
            { "Phendrana:Pike Access", new SpawnRoom(0xa8be6291, 3, 36) },
            { "Phendrana:Frost Cave Access", new SpawnRoom(0xa8be6291, 3, 37) },
            { "Phendrana:Hunter Cave Access", new SpawnRoom(0xa8be6291, 3, 38) },
            { "Phendrana:Control Tower", new SpawnRoom(0xa8be6291, 3, 39) },
            { "Phendrana:Research Core", new SpawnRoom(0xa8be6291, 3, 40) },
            { "Phendrana:Frost Cave", new SpawnRoom(0xa8be6291, 3, 41) },
            { "Phendrana:Hunter Cave", new SpawnRoom(0xa8be6291, 3, 42) },
            { "Phendrana:East Tower", new SpawnRoom(0xa8be6291, 3, 43) },
            { "Phendrana:Research Core Access", new SpawnRoom(0xa8be6291, 3, 44) },
            { "Phendrana:Save Station C", new SpawnRoom(0xa8be6291, 3, 45) },
            { "Phendrana:Upper Edge Tunnel", new SpawnRoom(0xa8be6291, 3, 46) },
            { "Phendrana:Lower Edge Tunnel", new SpawnRoom(0xa8be6291, 3, 47) },
            { "Phendrana:Chamber Access", new SpawnRoom(0xa8be6291, 3, 48) },
            { "Phendrana:Lake Tunnel", new SpawnRoom(0xa8be6291, 3, 49) },
            { "Phendrana:Aether Lab Entryway", new SpawnRoom(0xa8be6291, 3, 50) },
            { "Phendrana:Research Lab Aether", new SpawnRoom(0xa8be6291, 3, 51) },
            { "Phendrana:Phendrana's Edge", new SpawnRoom(0xa8be6291, 3, 52) },
            { "Phendrana:Gravity Chamber", new SpawnRoom(0xa8be6291, 3, 53) },
            { "Phendrana:Storage Cave", new SpawnRoom(0xa8be6291, 3, 54) },
            { "Phendrana:Security Cave", new SpawnRoom(0xa8be6291, 3, 55) },
            { "Tallon:Landing Site", new SpawnRoom(0x39f2de28, 4, 0) },
            { "Tallon:Gully", new SpawnRoom(0x39f2de28, 4, 1) },
            { "Tallon:Canyon Cavern", new SpawnRoom(0x39f2de28, 4, 2) },
            { "Tallon:Temple Hall", new SpawnRoom(0x39f2de28, 4, 3) },
            { "Tallon:Alcove", new SpawnRoom(0x39f2de28, 4, 4) },
            { "Tallon:Waterfall Cavern", new SpawnRoom(0x39f2de28, 4, 5) },
            { "Tallon:Tallon Canyon", new SpawnRoom(0x39f2de28, 4, 6) },
            { "Tallon:Temple Security Station", new SpawnRoom(0x39f2de28, 4, 7) },
            { "Tallon:Frigate Crash Site", new SpawnRoom(0x39f2de28, 4, 8) },
            { "Tallon:Transport Tunnel A", new SpawnRoom(0x39f2de28, 4, 9) },
            { "Tallon:Root Tunnel", new SpawnRoom(0x39f2de28, 4, 10) },
            { "Tallon:Temple Lobby", new SpawnRoom(0x39f2de28, 4, 11) },
            { "Tallon:Frigate Access Tunnel", new SpawnRoom(0x39f2de28, 4, 12) },
            { "Tallon:Overgrown Cavern", new SpawnRoom(0x39f2de28, 4, 13) },
            { "Tallon:Transport to Chozo Ruins West", new SpawnRoom(0x39f2de28, 4, 14) },
            { "Tallon:Root Cave", new SpawnRoom(0x39f2de28, 4, 15) },
            { "Tallon:Artifact Temple", new SpawnRoom(0x39f2de28, 4, 16) },
            { "Tallon:Main Ventilation Shaft Section C", new SpawnRoom(0x39f2de28, 4, 17) },
            { "Tallon:Transport Tunnel C", new SpawnRoom(0x39f2de28, 4, 18) },
            { "Tallon:Transport Tunnel B", new SpawnRoom(0x39f2de28, 4, 19) },
            { "Tallon:Arbor Chamber", new SpawnRoom(0x39f2de28, 4, 20) },
            { "Tallon:Main Ventilation Shaft Section B", new SpawnRoom(0x39f2de28, 4, 21) },
            { "Tallon:Transport to Chozo Ruins East", new SpawnRoom(0x39f2de28, 4, 22) },
            { "Tallon:Transport to Magmoor Caverns East", new SpawnRoom(0x39f2de28, 4, 23) },
            { "Tallon:Main Ventilation Shaft Section A", new SpawnRoom(0x39f2de28, 4, 24) },
            { "Tallon:Reactor Core", new SpawnRoom(0x39f2de28, 4, 25) },
            { "Tallon:Reactor Access", new SpawnRoom(0x39f2de28, 4, 26) },
            { "Tallon:Cargo Freight Lift to Deck Gamma", new SpawnRoom(0x39f2de28, 4, 27) },
            { "Tallon:Savestation", new SpawnRoom(0x39f2de28, 4, 28) },
            { "Tallon:Deck Beta Transit Hall", new SpawnRoom(0x39f2de28, 4, 29) },
            { "Tallon:Biohazard Containment", new SpawnRoom(0x39f2de28, 4, 30) },
            { "Tallon:Deck Beta Security Hall", new SpawnRoom(0x39f2de28, 4, 31) },
            { "Tallon:Biotech Research Area 1", new SpawnRoom(0x39f2de28, 4, 32) },
            { "Tallon:Deck Beta Conduit Hall", new SpawnRoom(0x39f2de28, 4, 33) },
            { "Tallon:Connection Elevator to Deck Beta", new SpawnRoom(0x39f2de28, 4, 34) },
            { "Tallon:Hydro Access Tunnel", new SpawnRoom(0x39f2de28, 4, 35) },
            { "Tallon:Great Tree Hall", new SpawnRoom(0x39f2de28, 4, 36) },
            { "Tallon:Great Tree Chamber", new SpawnRoom(0x39f2de28, 4, 37) },
            { "Tallon:Transport Tunnel D", new SpawnRoom(0x39f2de28, 4, 38) },
            { "Tallon:Life Grove Tunnel", new SpawnRoom(0x39f2de28, 4, 39) },
            { "Tallon:Transport Tunnel E", new SpawnRoom(0x39f2de28, 4, 40) },
            { "Tallon:Transport to Chozo Ruins South", new SpawnRoom(0x39f2de28, 4, 41) },
            { "Tallon:Life Grove", new SpawnRoom(0x39f2de28, 4, 42) },
            { "Tallon:Transport to Phazon Mines East", new SpawnRoom(0x39f2de28, 4, 43) },
            { "Mines:Transport to Tallon Overworld South", new SpawnRoom(0xb1ac4d65, 5, 0) },
            { "Mines:Quarry Access", new SpawnRoom(0xb1ac4d65, 5, 1) },
            { "Mines:Main Quarry", new SpawnRoom(0xb1ac4d65, 5, 2) },
            { "Mines:Waste Disposal", new SpawnRoom(0xb1ac4d65, 5, 3) },
            { "Mines:Save Station Mines A", new SpawnRoom(0xb1ac4d65, 5, 4) },
            { "Mines:Security Access A", new SpawnRoom(0xb1ac4d65, 5, 5) },
            { "Mines:Ore Processing", new SpawnRoom(0xb1ac4d65, 5, 6) },
            { "Mines:Mine Security Station", new SpawnRoom(0xb1ac4d65, 5, 7) },
            { "Mines:Research Access", new SpawnRoom(0xb1ac4d65, 5, 8) },
            { "Mines:Storage Depot B", new SpawnRoom(0xb1ac4d65, 5, 9) },
            { "Mines:Elevator Access A", new SpawnRoom(0xb1ac4d65, 5, 10) },
            { "Mines:Security Access B", new SpawnRoom(0xb1ac4d65, 5, 11) },
            { "Mines:Storage Depot A", new SpawnRoom(0xb1ac4d65, 5, 12) },
            { "Mines:Elite Research", new SpawnRoom(0xb1ac4d65, 5, 13) },
            { "Mines:Elevator A", new SpawnRoom(0xb1ac4d65, 5, 14) },
            { "Mines:Elite Control Access", new SpawnRoom(0xb1ac4d65, 5, 15) },
            { "Mines:Elite Control", new SpawnRoom(0xb1ac4d65, 5, 16) },
            { "Mines:Maintenance Tunnel", new SpawnRoom(0xb1ac4d65, 5, 17) },
            { "Mines:Ventilation Shaft", new SpawnRoom(0xb1ac4d65, 5, 18) },
            { "Mines:Phazon Processing Center", new SpawnRoom(0xb1ac4d65, 5, 19) },
            { "Mines:Omega Research", new SpawnRoom(0xb1ac4d65, 5, 20) },
            { "Mines:Transport Access", new SpawnRoom(0xb1ac4d65, 5, 21) },
            { "Mines:Processing Center Access", new SpawnRoom(0xb1ac4d65, 5, 22) },
            { "Mines:Map Station Mines", new SpawnRoom(0xb1ac4d65, 5, 23) },
            { "Mines:Dynamo Access", new SpawnRoom(0xb1ac4d65, 5, 24) },
            { "Mines:Transport to Magmoor Caverns South", new SpawnRoom(0xb1ac4d65, 5, 25) },
            { "Mines:Elite Quarters", new SpawnRoom(0xb1ac4d65, 5, 26) },
            { "Mines:Central Dynamo", new SpawnRoom(0xb1ac4d65, 5, 27) },
            { "Mines:Elite Quarters Access", new SpawnRoom(0xb1ac4d65, 5, 28) },
            { "Mines:Quarantine Access A", new SpawnRoom(0xb1ac4d65, 5, 29) },
            { "Mines:Save Station Mines B", new SpawnRoom(0xb1ac4d65, 5, 30) },
            { "Mines:Metroid Quarantine B", new SpawnRoom(0xb1ac4d65, 5, 31) },
            { "Mines:Metroid Quarantine A", new SpawnRoom(0xb1ac4d65, 5, 32) },
            { "Mines:Quarantine Access B", new SpawnRoom(0xb1ac4d65, 5, 33) },
            { "Mines:Save Station Mines C", new SpawnRoom(0xb1ac4d65, 5, 34) },
            { "Mines:Elevator Access B", new SpawnRoom(0xb1ac4d65, 5, 35) },
            { "Mines:Fungal Hall B", new SpawnRoom(0xb1ac4d65, 5, 36) },
            { "Mines:Elevator B", new SpawnRoom(0xb1ac4d65, 5, 37) },
            { "Mines:Missile Station Mines", new SpawnRoom(0xb1ac4d65, 5, 38) },
            { "Mines:Phazon Mining Tunnel", new SpawnRoom(0xb1ac4d65, 5, 39) },
            { "Mines:Fungal Hall Access", new SpawnRoom(0xb1ac4d65, 5, 40) },
            { "Mines:Fungal Hall A", new SpawnRoom(0xb1ac4d65, 5, 41) },
            { "Magmoor:Transport to Chozo Ruins North", new SpawnRoom(0x3ef8237c, 6, 0) },
            { "Magmoor:Burning Trail", new SpawnRoom(0x3ef8237c, 6, 1) },
            { "Magmoor:Lake Tunnel", new SpawnRoom(0x3ef8237c, 6, 2) },
            { "Magmoor:Save Station Magmoor A", new SpawnRoom(0x3ef8237c, 6, 3) },
            { "Magmoor:Lava Lake", new SpawnRoom(0x3ef8237c, 6, 4) },
            { "Magmoor:Pit Tunnel", new SpawnRoom(0x3ef8237c, 6, 5) },
            { "Magmoor:Triclops Pit", new SpawnRoom(0x3ef8237c, 6, 6) },
            { "Magmoor:Monitor Tunnel", new SpawnRoom(0x3ef8237c, 6, 7) },
            { "Magmoor:Storage Cavern", new SpawnRoom(0x3ef8237c, 6, 8) },
            { "Magmoor:Monitor Station", new SpawnRoom(0x3ef8237c, 6, 9) },
            { "Magmoor:Transport Tunnel A", new SpawnRoom(0x3ef8237c, 6, 10) },
            { "Magmoor:Warrior Shrine", new SpawnRoom(0x3ef8237c, 6, 11) },
            { "Magmoor:Shore Tunnel", new SpawnRoom(0x3ef8237c, 6, 12) },
            { "Magmoor:Transport to Phendrana Drifts North", new SpawnRoom(0x3ef8237c, 6, 13) },
            { "Magmoor:Fiery Shores", new SpawnRoom(0x3ef8237c, 6, 14) },
            { "Magmoor:Transport Tunnel B", new SpawnRoom(0x3ef8237c, 6, 15) },
            { "Magmoor:Transport to Tallon Overworld West", new SpawnRoom(0x3ef8237c, 6, 16) },
            { "Magmoor:Twin Fires Tunnel", new SpawnRoom(0x3ef8237c, 6, 17) },
            { "Magmoor:Twin Fires", new SpawnRoom(0x3ef8237c, 6, 18) },
            { "Magmoor:North Core Tunnel", new SpawnRoom(0x3ef8237c, 6, 19) },
            { "Magmoor:Geothermal Core", new SpawnRoom(0x3ef8237c, 6, 20) },
            { "Magmoor:Plasma Processing", new SpawnRoom(0x3ef8237c, 6, 21) },
            { "Magmoor:South Core Tunnel", new SpawnRoom(0x3ef8237c, 6, 22) },
            { "Magmoor:Magmoor Workstation", new SpawnRoom(0x3ef8237c, 6, 23) },
            { "Magmoor:Workstation Tunnel", new SpawnRoom(0x3ef8237c, 6, 24) },
            { "Magmoor:Transport Tunnel C", new SpawnRoom(0x3ef8237c, 6, 25) },
            { "Magmoor:Transport to Phazon Mines West", new SpawnRoom(0x3ef8237c, 6, 26) },
            { "Magmoor:Transport to Phendrana Drifts South", new SpawnRoom(0x3ef8237c, 6, 27) },
            { "Magmoor:Save Station Magmoor B", new SpawnRoom(0x3ef8237c, 6, 28) },
            { "Crater:Crater Entry Point", new SpawnRoom(0xc13b09d1, 7, 0) },
            { "Crater:Crater Tunnel A", new SpawnRoom(0xc13b09d1, 7, 1) },
            { "Crater:Phazon Core", new SpawnRoom(0xc13b09d1, 7, 2) },
            { "Crater:Crater Missile Station", new SpawnRoom(0xc13b09d1, 7, 3) },
            { "Crater:Crater Tunnel B", new SpawnRoom(0xc13b09d1, 7, 4) },
            { "Crater:Phazon Infusion Chamber", new SpawnRoom(0xc13b09d1, 7, 5) },
            { "Crater:Subchamber One", new SpawnRoom(0xc13b09d1, 7, 6) },
            { "Crater:Subchamber Two", new SpawnRoom(0xc13b09d1, 7, 7) },
            { "Crater:Subchamber Three", new SpawnRoom(0xc13b09d1, 7, 8) },
            { "Crater:Subchamber Four", new SpawnRoom(0xc13b09d1, 7, 9) },
            { "Crater:Subchamber Five", new SpawnRoom(0xc13b09d1, 7, 10) },
            { "Crater:Metroid Prime Lair", new SpawnRoom(0xc13b09d1, 7, 11) }
        };
    }
}
